// demo/react/src/windows/WelcomeApp.tsx
const styles: React.CSSProperties = {
  padding: 24,
  fontFamily: 'Segoe UI, sans-serif',
  height: '100%',
  display: 'flex',
  flexDirection: 'column',
  gap: 12,
}

export default function WelcomeApp() {
  return (
    <div style={styles}>
      <h2 style={{ margin: 0, fontSize: 18, color: '#333' }}>🖥 歡迎使用 WebOS-Core</h2>
      <p style={{ color: '#555', lineHeight: 1.7, margin: 0 }}>
        React 包裝層示範，展示核心特性：
      </p>
      <ul style={{ color: '#444', lineHeight: 2, paddingLeft: 20, margin: 0 }}>
        <li>✅ <code>useWindowManager</code> hook</li>
        <li>✅ <code>createPortal</code> 將元件渲染進視窗 DOM</li>
        <li>✅ 狀態自動保留（最小化不銷毀元件）</li>
        <li>✅ <strong>Snap 吸附</strong>：拖曳靠近邊緣自動對齊</li>
        <li>✅ <strong>主題切換</strong>：點擊 Dock 下方 ☀️/🌙 切換亮/暗色主題</li>
      </ul>
      <p style={{ color: '#888', fontSize: 12, marginTop: 'auto' }}>
        點擊左側 Dock 開啟其他示範視窗 →
      </p>
    </div>
  )
}

// demo/vue/src/windows/WelcomeApp.vue
<template>
  <div class="welcome">
    <h2>🖥 WebOS-Core</h2>
    <p>框架無關的網頁視窗管理引擎 <code>v0.1.0</code></p>
    <ul>
      <li>✅ 純 TypeScript，零框架依賴</li>
      <li>✅ 拖曳 / 縮放 / 置頂 / 最小化 / 最大化</li>
      <li>✅ <strong>Snap 吸附</strong>：拖曳靠近邊緣自動對齊</li>
      <li>✅ Keep-Alive：最小化不銷毀 Vue 元件狀態</li>
      <li>✅ 跨視窗 EventBus</li>
      <li>✅ Vue 3 Composable 整合</li>
      <li>✅ <strong>主題切換</strong>：點擊 Dock 下方 ☀️/🌙 切換亮/暗色主題</li>
    </ul>
    <p class="hint">點擊左側 Dock 圖示開啟應用程式 👈</p>
  </div>
</template>

<style scoped>
.welcome {
  padding: 20px;
  line-height: 1.8;
}
h2 {
  margin-top: 0;
  color: #1a73e8;
  font-size: 1.3rem;
}
ul {
  padding-left: 20px;
  color: #555;
  margin: 10px 0;
}
code {
  background: #f0f4ff;
  padding: 1px 6px;
  border-radius: 4px;
  font-size: 0.85em;
  color: #1a73e8;
}
.hint {
  margin-top: 12px;
  color: #888;
  font-size: 0.9rem;
}
</style>
